volumes:
  postgres_data:

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    volumes:
      - ./src:/app/src
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: trackntrain_backend
    ports:
      - '8000:8000'
    environment:
      ENV: test
      SECRET_KEY: 123456789
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      DATABASE_URL: postgresql+asyncpg://user:user@91.169.178.154:5400/postgres